// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdjustBalanceArgs {
    pub uuid: String,
    pub amount: i64,
}

impl From<AdjustBalanceArgs> for super::Reducer {
    fn from(args: AdjustBalanceArgs) -> Self {
        Self::AdjustBalance {
            uuid: args.uuid,
            amount: args.amount,
        }
    }
}

impl __sdk::InModule for AdjustBalanceArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `adjust_balance`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait adjust_balance {
    /// Request that the remote module invoke the reducer `adjust_balance` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`adjust_balance:adjust_balance_then`] to run a callback after the reducer completes.
    fn adjust_balance(&self, uuid: String, amount: i64) -> __sdk::Result<()> {
        self.adjust_balance_then(uuid, amount, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `adjust_balance` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn adjust_balance_then(
        &self,
        uuid: String,
        amount: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl adjust_balance for super::RemoteReducers {
    fn adjust_balance_then(
        &self,
        uuid: String,
        amount: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AdjustBalanceArgs { uuid, amount }, callback)
    }
}
