// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EnsurePlayerProfileArgs {
    pub uuid: String,
    pub username: String,
}

impl From<EnsurePlayerProfileArgs> for super::Reducer {
    fn from(args: EnsurePlayerProfileArgs) -> Self {
        Self::EnsurePlayerProfile {
            uuid: args.uuid,
            username: args.username,
        }
    }
}

impl __sdk::InModule for EnsurePlayerProfileArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ensure_player_profile`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ensure_player_profile {
    /// Request that the remote module invoke the reducer `ensure_player_profile` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ensure_player_profile:ensure_player_profile_then`] to run a callback after the reducer completes.
    fn ensure_player_profile(&self, uuid: String, username: String) -> __sdk::Result<()> {
        self.ensure_player_profile_then(uuid, username, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `ensure_player_profile` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ensure_player_profile_then(
        &self,
        uuid: String,
        username: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ensure_player_profile for super::RemoteReducers {
    fn ensure_player_profile_then(
        &self,
        uuid: String,
        username: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(EnsurePlayerProfileArgs { uuid, username }, callback)
    }
}
