// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerProfile {
    pub uuid: String,
    pub username: String,
}

impl __sdk::InModule for PlayerProfile {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerProfile`.
///
/// Provides typed access to columns for query building.
pub struct PlayerProfileCols {
    pub uuid: __sdk::__query_builder::Col<PlayerProfile, String>,
    pub username: __sdk::__query_builder::Col<PlayerProfile, String>,
}

impl __sdk::__query_builder::HasCols for PlayerProfile {
    type Cols = PlayerProfileCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerProfileCols {
            uuid: __sdk::__query_builder::Col::new(table_name, "uuid"),
            username: __sdk::__query_builder::Col::new(table_name, "username"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerProfile`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerProfileIxCols {
    pub uuid: __sdk::__query_builder::IxCol<PlayerProfile, String>,
}

impl __sdk::__query_builder::HasIxCols for PlayerProfile {
    type IxCols = PlayerProfileIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerProfileIxCols {
            uuid: __sdk::__query_builder::IxCol::new(table_name, "uuid"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerProfile {}
