// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetBalanceArgs {
    pub uuid: String,
    pub new_balance: i64,
}

impl From<SetBalanceArgs> for super::Reducer {
    fn from(args: SetBalanceArgs) -> Self {
        Self::SetBalance {
            uuid: args.uuid,
            new_balance: args.new_balance,
        }
    }
}

impl __sdk::InModule for SetBalanceArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_balance`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_balance {
    /// Request that the remote module invoke the reducer `set_balance` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_balance:set_balance_then`] to run a callback after the reducer completes.
    fn set_balance(&self, uuid: String, new_balance: i64) -> __sdk::Result<()> {
        self.set_balance_then(uuid, new_balance, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_balance` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_balance_then(
        &self,
        uuid: String,
        new_balance: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_balance for super::RemoteReducers {
    fn set_balance_then(
        &self,
        uuid: String,
        new_balance: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetBalanceArgs { uuid, new_balance }, callback)
    }
}
